### ISSUE TITLE
[1.14.2] Overriding vanilla shears

### ISSUE THREAD

**Issue by kwpugh** [Sinhika/SimpleOres2#19]
Hi,

This may not be an issue, it may just be me.

Simple Ores overrides vanilla jsons for leaves and grass and adds in modded shears as valid tools.

I started to do the same thing.

I have SimpleOres in my test modpack.   While testing your shears and mine, neither drops grass or leaves.   With just your shears OR just mine, everything is fine.

Are we overriding each other?   I'm not sure how the vanilla data packs within mods is supposed to in those cases.

Regards.

**Comment by Sinhika** [comment]
It's a serious problem in that shears don't work as shears unless they are specified by id (not tag) in the loot tables. (Except sheep, they are fixed for sheep). This is terrible for mod compatibility, unless we can figure out how to append things to the loot tables rather than overriding them. I believe the Forge devs are working on the problem, because I did see stubs for using IShearable for blocks as well as entities, but it wasn't functional as of the version of Forge I compiled against. Nothing in the changelog yet, either, though I haven't checked today.

If and when they fix shears, I'll ditch the custom loot tables for leaf blocks.

**Comment by cech12** [comment]
You can do loot table injections like I have done in my mod: https://github.com/cech12/CeramicShears/commit/330341daf2b827321455725adf3f50ec49c9cb82

Or you can wait until the forge:shears tag is included into Forge. :)

**Comment by Sinhika** [comment]
I finally fixed it with GlobalLootModifiers in 1.15.2. I'll eventually backport it to 1.14.4, along with the other Simple Ores mods.  (They've recently backported the GlobalLootModifier stuff to Forge for 1.14.4).

You might want to look at that solution--it worked out really well.

**Comment by kwpugh** [comment]
Thanks for the heads-up
