### ISSUE TITLE
Mod support for Silences Mechinisms Mod

### ISSUE THREAD

**Issue by CarlucciMods** [Sinhika/SimpleOres2#24]
be able to put your ores in the crusher, as of right now will not let you.  Greast Work on your mod....please and thank you

**Comment by Sinhika** [comment]
I just tested SilentMechanisms-1.15.2-0.7.6+57 with Simple Ores. It crushes Simple Ores copper ore and tin ore just fine. It does not know about adamantium and mythril ores as those are not ores that it comes with recipes for, or uses, and there is no 'crushed ore' item for those ores in Silent's Mechanisms. I won't say "no, never" about adding that support, but it's way down on my priority list, and if Silent doesn't port their stuff to 1.16, it will fall off my priority list, because adding other mod support stuff for one major version and then ripping it out the next version is a pain. However, if other tech mods catch up and also use the 'crushed ore'/'ore chunks''/'ore dust' mechanism, I'll consider it.

**Comment by Wiccat** [comment]
FWIW Silent's mods are all fully 1.16.1 compatible now (1.16.2 is a problem because of world-gen changes):
 * Adding uses for mythril/adamantium is fairly eaisly done with a data pack + resource pack combination and turning them into SilentGear materials (I'm using working copies my MP world now) and it allows Mythril and Adamantium to be used by SilentGear and proceseed through SilentMechanism machines. 
 * Creating salvaging recipes so the SimpleOres tools can be processed through the Salvager is simple but tedious becuase you need one for each metal-based item.  
 * Using the JAOPCA mod allows for crushing Mythril and Adamantium into chunks, but not dust - as SimpleOres doesn't provide a dust for those metals.  If SimpleOres had a dust component for those metals, then SimpleOres + JAOPCA would solve this issue handily.

**Comment by Sinhika** [comment]
Implemented Silent's Mechanisms crusher recipes and dust and ore chunk items for Mythril and Adamantium. Onyx will not be crushable; the gems are brittle and would shatter in a crusher. Upgrade currently in 1.15.2, will be ported to 1.14.4 and 1.16.3 as time allows.
