### ISSUE TITLE
Ores don't have forge tags

### ISSUE THREAD

**Issue by kitsu** [Sinhika/SimpleOres2#43]
I'm using CC:Tweaked, and my mining program is checking for the `forege:ores` tag to determine what blocks it should dig.  
I noticed that my turtle passed right by an ore, and when I checked it was Simple Ores tin.

After double checking with `turtle.inspect()` it looks like none of your ores have any tags?  
I would expect at least `forge:ores` and `forge:ores/copper` (or whatever ore it is).

Thanks,

SimpleCoreLib-1.16.4-2.0.2.0
SimpleOres2-1.16.4-2.4.2.0
Forge 35.0.7
MC 1.16.4

**Comment by Sinhika** [comment]
... It helps if I don't have the data-generation code that creates block tags commented out. Fixed by commit 44ead01a98d1359f8e377efe08aa24165f17dd9b. ~~Issue probably needs to be addressed in 1.15.2 & 1.14.4 branches as well~~  No, 1.15.2 and 1.14.4 have their tags okay. Fixed in new release on CurseForge, SimpleOres 1.16.4-2.4.2.1
