### ISSUE TITLE
[1.18.2-4.1.2.0] Some bugs and sound inconsistencies

### ISSUE THREAD

**Issue by Thombias** [Sinhika/SimpleOres2#61]
A few bugs (and missing features?) i noticed while playtesting the mod with my new textures:
- Deepslate tin ore doesn't appear to drop more with Fortune enchantments. I always kept getting 1-4 drops instead of 1-8 drops from regular stone tin ore blocks. (Personally i think tin should drop 2-5 raw ores similar to copper without fortune anyway so you're even more inclined to use it for decoration.)
- The doors for all materials drop twice when mined (duplicate bug)
- The zoom effect when drawing a vanilla bow is missing for the mythril and onyx bows (unsure how possible it is to implement this)

And here some sound inconsistencies i've noticed when comparing them to vanilla:
- Deepslate ore blocks for tin, mythril and adamantium play normal stone sounds instead of deepslate ones.
- Block of raw tin, mythril & adamantium play iron block sounds instead of normal stone sounds like vanilla
- Block of Onyx & Bricks play stone sounds instead of iron block sounds (Diamond uses them so i think onyx should too)

Of course the sound inconsistencies are just me being super picky but i really want this mod to be the best it could be. The zoom effect doesn't matter too much but if these little issues could be fixed it would really help making this mod more polished. :D

I don't know how open you're to feature requests but i noticed while working on the textures that copper doors, bars and pressure plates don't have oxidized textures. Would you implement that feature at some point? I know this will require more textures but i can try and provide them for you if needed.

**Comment by Sinhika** [comment]
Nice catch. 
- fixed the deepslate tin ore not dropping multiple raw metal.
- fixed the doors dropping 2x.
- didn't know there was a difference between deepslate stone and stone sounds. Fixed, but not tested yet (dev env doesn't have sound).
- Did not know that raw metal blocks used stone sounds. Fixed.
- Onyx is a stone. It should sound like stone. Vanilla making diamond sound like metal is vanilla's problem.
- Bow zooming got temporarily dropped in porting, because the events were changed.

Fixes included in [SimpleOres2-1.18.2-4.1.2.3.jar](https://www.curseforge.com/minecraft/mc-mods/simpleores/files/3783272) and later.

**Comment by Sinhika** [comment]
- fixed missing bow zoom with release [SimpleOres2-1.18.2-4.1.2.4.jar](https://www.curseforge.com/minecraft/mc-mods/simpleores/files/3793071)
